In [1]:
import os
os.environ["WANDB_DISABLED"] = "true"

import sys
# sys.path = ['/home/jxm3/research/retrieval/inversion'] + sys.path
sys.path = [
    p for p in sys.path
    if p not in ['/home/jxm3/research/prompting/imodelsX', '/home/jxm3/research/prompting/tree-prompt']
]
sys.path.append('/home/jxm3/research/retrieval/inversion')

%load_ext autoreload
%autoreload 2

In [2]:
print(sys.path)

['/home/jxm3/research/retrieval/inversion/notebooks', '/home/jxm3/.conda/envs/torch/lib/python310.zip', '/home/jxm3/.conda/envs/torch/lib/python3.10', '/home/jxm3/.conda/envs/torch/lib/python3.10/lib-dynload', '', '/home/jxm3/.conda/envs/torch/lib/python3.10/site-packages', '/home/jxm3/random/slurmpy', '/home/jxm3/.conda/envs/torch/lib/python3.10/site-packages/mpmath-1.2.1-py3.10.egg', '/home/jxm3/research/retrieval/inversion']


In [6]:
import analyze_utils

# https://wandb.ai/jack-morris/emb-inv-bow-1/runs/a765aaaf0a0e689659a5a6a00f6a2e84/overview?workspace=user-jxmorris12
checkpoint_folder = "/home/jxm3/research/retrieval/inversion/saves/4fbfb4a93eb0d64d3ca837b17d0a47d3/"
trainer = analyze_utils.load_trainer(checkpoint_folder)

Loading trainer for analysis – setting --do_eval=1


/home/jxm3/.conda/envs/torch/lib/python3.10/site-packages/transformers/models/t5/tokenization_t5_fast.py:155: FutureWarning: This tokenizer was incorrectly instantiated with a model max length of 512 which will be corrected in Transformers v5.
For now, this behavior is kept to avoid breaking backwards compatibility when padding/encoding with `truncation is True`.
- Be aware that you SHOULD NOT rely on t5-base automatically truncating your input to 512 when padding/encoding.
- If you want to encode/pad to sequences longer than 512 you can either instantiate this tokenizer with `model_max_length` or pass `max_length` when encoding/padding.
- To avoid this warning, please instantiate this tokenizer with `model_max_length` set to your preferred value.
  warnings.warn(


  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

Running tokenizer on dataset:   0%|          | 0/11332 [00:00<?, ? examples/s]

[nltk_data] Downloading package wordnet to /home/jxm3/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt to /home/jxm3/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /home/jxm3/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


================ Begin trainer sanity check ================
	Input to encode -> Twas brillig, and the slithy toves, Did gyre and gimble in the wabe, All mimsy were the borogoves, And the mome raths outgrabe.
> /home/jxm3/research/retrieval/inversion/models/inversion_bow.py(59)generate()
     57         max_length = inputs.get("input_ids", inputs["embedder_input_ids"]).shape[1]
     58         import pdb; pdb.set_trace()
---> 59         return logits.topk(max_length, dim=1).indices
     60 
     61     def call_embedding_model(



ipdb>  logits.topk(max_length, dim=1).indices


tensor([[    0,     6,    62,     5,     2,   114,     7,  2295,    14,    10,
            50,   121,     4,    46,    16,  2287,  2159, 18032,   345,    51,
            39,    12,    36,  1151,    25,  4231,    59,   763,   129,   209,
            31,  5729,   953,    77,  3541,   116,    11,   119,   107,     8,
            35,  3971,  4663,   724,  7001,  4751,  5599,   276,  1764,  5571,
          7309,    30,    15,    22,    28,   108,   968,  1262]],
       device='cuda:0')


ipdb>  inputs.get("input_ids")
ipdb>  inputs.get("input_ids", inputs["embedder_input_ids"])


tensor([[  332,  9491,     3,  2160,    40,  2825,     6,    11,     8,     3,
             7, 18800,    63,    12,   162,     7,     6,  3963,     3,   122,
            63,    60,    11,     3,   122,   603,  2296,    16,     8,  8036,
           346,     6,   432,  1337,    51,     7,    63,   130,     8,     3,
         14901,  9527,    15,     7,     6,   275,     8,  3912,    15,     3,
          1795,   107,     7,    91,  3484,   346,     5,     1]],
       device='cuda:0')


ipdb>  p logits


tensor([[ 10.2401,  -4.1152,   1.9175,  ..., -43.8247, -43.5744, -43.4407]],
       device='cuda:0')


ipdb>  p logits.argmax()


tensor(0, device='cuda:0')


ipdb>  p logits[:,1:].argmax()


tensor(5, device='cuda:0')


ipdb>  p (-logits).argsort()


tensor([[    0,     6,    62,  ..., 29987, 30964, 17328]], device='cuda:0')


ipdb>  p logits.topk(10).values


tensor([[10.2401,  2.7274,  2.3547,  2.1285,  1.9175,  1.5308,  1.3781,  1.2467,
          1.2268,  1.1331]], device='cuda:0')


ipdb>  p logits.sigmoid().topk(10).values


tensor([[1.0000, 0.9386, 0.9133, 0.8936, 0.8719, 0.8221, 0.7987, 0.7767, 0.7733,
         0.7564]], device='cuda:0')


ipdb>  p (logits.sigmoid() < 0).any()


tensor(False, device='cuda:0')


ipdb>  p (logits.sigmoid() > 0.5).nonzero()


tensor([[   0,    0],
        [   0,    2],
        [   0,    4],
        [   0,    5],
        [   0,    6],
        [   0,    7],
        [   0,   10],
        [   0,   14],
        [   0,   16],
        [   0,   46],
        [   0,   50],
        [   0,   62],
        [   0,  114],
        [   0,  121],
        [   0, 2295]], device='cuda:0')


ipdb>  p (logits.flatten().sigmoid() > 0.5).nonzero()


tensor([[   0],
        [   2],
        [   4],
        [   5],
        [   6],
        [   7],
        [  10],
        [  14],
        [  16],
        [  46],
        [  50],
        [  62],
        [ 114],
        [ 121],
        [2295]], device='cuda:0')


ipdb>  p self.tokenizer.decode(p (logits.flatten().sigmoid() > 0.5).nonzero().flatten())


*** NameError: name 'p' is not defined


ipdb>   self.tokenizer.decode((logits.flatten().sigmoid() > 0.5).nonzero().flatten())


'<pad><unk>X.,s: fill in an la we like"uch'


ipdb>  logits


tensor([[ 10.2401,  -4.1152,   1.9175,  ..., -43.8247, -43.5744, -43.4407]],
       device='cuda:0')


ipdb>  labels = inputs["embedder_input_ids"]
ipdb>  labels


tensor([[  332,  9491,     3,  2160,    40,  2825,     6,    11,     8,     3,
             7, 18800,    63,    12,   162,     7,     6,  3963,     3,   122,
            63,    60,    11,     3,   122,   603,  2296,    16,     8,  8036,
           346,     6,   432,  1337,    51,     7,    63,   130,     8,     3,
         14901,  9527,    15,     7,     6,   275,     8,  3912,    15,     3,
          1795,   107,     7,    91,  3484,   346,     5,     1]],
       device='cuda:0')


ipdb>  self.bow_loss(logits, labels)


*** ValueError: Target size (torch.Size([1, 32128])) must be the same as input size (torch.Size([1, 32127]))


ipdb>  logits.shape


torch.Size([1, 32127])


ipdb>  exit


In [32]:
trainer.sanity_decode()

================ Begin trainer sanity check ================
	Input to encode -> Twas brillig, and the slithy toves, Did gyre and gimble in the wabe, All mimsy were the borogoves, And the mome raths outgrabe.
	Decoded output -> sy, b theblee andmg. wast mobri boreberl of Theberdbiere came wereworite ma so gr; toly sia bemosliesiesgla plzieerskingdigbble' ininleby Go
================ End trainer sanity check ================


In [17]:
trainer.sanity_decode()

================ Begin trainer sanity check ================
	Input to encode -> Twas brillig, and the slithy toves, Did gyre and gimble in the wabe, All mimsy were the borogoves, And the mome raths outgrabe.
	Decoded output -> sy, b theblee andmg. wast mobri boreberl of Theberdbiere came wereworite ma so gr; toly sia bemosliesiesgla plzieerskingdigbble' ininleby Go
================ End trainer sanity check ================


In [20]:
trainer.evaluate(
    eval_dataset=trainer.eval_dataset["nq"]
)

skull of smooth the.s, and infantural bones mannert that toa softletonular in aretraumatic The unlike with detailsul character remains
to the character of the sutures of the skull which, like those of the infant skull, are relatively smooth and untortuous. In fact



Winter the  to won winter South and win was team, medal Australiaa who Australian He. for of gold World individual in S Northern Team Olympics from-
individual from the Southern Hemisphere, to win a Winter Olympic gold medal and was also part of the short track relay team that won Australia'



rights. equality and discrimin workers,  workplace gay protected LGBTs the of to work that right equal same employees straight agreeda they agree should peopled were
the same rights as straight people, while 15% disagreed. Additionally, 69% agreed that they should be protected from workplace discrimination. 13% of H


{'eval_loss': 0.0023660382721573114,
 'eval_bleu_score': 0.30800504075285257,
 'eval_meteor_score': 0.222961078407515,
 'eval_rouge_score': 0.3596046073030128,
 'eval_bert_score': 0.8157957574129104,
 'eval_emb_cos_sim': 0.704466700553894,
 'eval_runtime': 10.2924,
 'eval_samples_per_second': 48.58,
 'eval_steps_per_second': 0.097}

In [33]:
trainer.evaluate(
    eval_dataset=trainer.eval_dataset["wikibio"]
)

li known ( asI Michael ila II thelik, ofiche "KIII alsoano) I Church-dsf III
pope michael iii of alexandria -lrb- also known as khail i



 is tennis. playerajun () Chinesehui He table male Jun female the who Huheie former and has- professional Fu men of high
hui jun is a male former table tennis player from china.



 (born is)ba Turkish Ourrk 7rikturtürlnst July born. Turkeyy Rz;o November
okan ztürk -lrb- born 30 november 1977 -rrb- is a tur


{'eval_loss': 0.0023790744598954916,
 'eval_bleu_score': 0.0815640354794625,
 'eval_meteor_score': 0.10922318446591002,
 'eval_rouge_score': 0.1768731644551103,
 'eval_bert_score': 0.7914543685913086,
 'eval_emb_cos_sim': 0.6554672718048096,
 'eval_runtime': 3.3372,
 'eval_samples_per_second': 149.828,
 'eval_steps_per_second': 0.3}